import { ReduxModule } from 'react-pages'

// Using an explicit Redux event namespace here to prevent
// autogenerated Redux event name collision due to different
// `node_modules/react-pages` packages being used.
const redux = new ReduxModule('NOTIFICATIONS')

const setNotification = redux.simpleAction(
	(state, notification) => ({
		...state,
		notification
	})
)

export const notify = (content, options) => {
	return setNotification({ content, ...options })
}

export default redux.reducer()