import { ReduxModule } from 'react-pages'

import { createPromise } from '../components/OkCancelDialogPromise'

// Using an explicit Redux event namespace here to prevent
// autogenerated Redux event name collision due to different
// `node_modules/react-pages` packages being used.
const redux = new ReduxModule('OK_CANCEL_DIALOG')

const onShowOkCancelDialog = redux.simpleAction(
	(state, contentAndOptions) => ({
		...state,
		...contentAndOptions,
		isOpen: true
	})
)

export const okCancelDialog = (content, options) => {
	createPromise()
	return onShowOkCancelDialog({ content, ...options })
}

export const close = redux.simpleAction(
	(state) => ({
		...state,
		isOpen: false
	})
)

export default redux.reducer()