import { ReduxModule } from 'react-website'

import { createPromise } from '../components/OkCancelDialogPromise'

// Using an explicit Redux event namespace here to prevent
// autogenerated Redux event name collision due to different
// `node_modules/react-website` packages being used.
const redux = new ReduxModule('OK_CANCEL_DIALOG')

export const okCancelDialog = redux.simpleAction(
	(content, options) => {
		createPromise()
		return ({ content, ...options })
	},
	(state, data) => ({
		...state,
		...data,
		isOpen: true
	})
)

export const close = redux.simpleAction(
	(state) => ({
		...state,
		isOpen: false
	})
)

export default redux.reducer()