import { ReduxModule } from 'react-pages'

// Using an explicit Redux event namespace here to prevent
// autogenerated Redux event name collision due to different
// `node_modules/react-pages` packages being used.
const redux = new ReduxModule('SLIDESHOW')

const onOpenSlideshow = redux.simpleAction(
	(state, args) => ({
		...state,
		...args,
		isOpen: true
	})
)

export const openSlideshow = (pictures, index, options) => {
	return onOpenSlideshow({ pictures, index, ...options })
}

export const closeSlideshow = redux.simpleAction(
	(state, event) => ({
		...state,
		pictures: undefined,
		index: undefined,
		slideshowMode: undefined,
		isOpen: false
	})
)

export default redux.reducer()