import { ReduxModule } from 'react-website'

// Using an explicit Redux event namespace here to prevent
// autogenerated Redux event name collision due to different
// `node_modules/react-website` packages being used.
const redux = new ReduxModule('SLIDESHOW')

export const openSlideshow = redux.simpleAction(
	(pictures, index, options) => ({ pictures, index, ...options }),
	(state, args) => ({
		...state,
		...args,
		isOpen: true
	})
)

export const closeSlideshow = redux.simpleAction(
	() => ({}),
	(state, event) => ({
		...state,
		pictures: undefined,
		index: undefined,
		slideshowMode: undefined,
		isOpen: false
	})
)

export default redux.reducer()