/**
 * Converts post content to text.
 * @param  {object} post
 * @param  {object} options — `{ messages, excludeQuotes }`
 * @return {string}
 */
export default function getPostText(post, options = {}) {
	if (!post.content) {
		return ''
	}
	// Simple case optimization.
	if (typeof post.content === 'string') {
		return post.content
	}
	// Concatenate post paragraphs' text.
	return post.content.map((paragraph) => {
		return getContentText(paragraph, {
			...options,
			attachments: post.attachments
		})
	}).filter(_ => _).join('\n\n')
}

function getContentText(content, options) {
	if (Array.isArray(content)) {
		content = removePostLinks(content)
		if (options.excludeQuotes) {
			content = removeQuotes(content)
		}
		return content.map(_ => getContentText(_, options)).join('')
	}
	if (typeof content === 'string') {
		return content
	}
	const part = content
	const getContent = () => getContentText(part.content, options)
	switch (part.type) {
		case 'quote':
			if (options.excludeQuotes) {
				return ''
			}
			if (part.source) {
				return `«${getContent()}» — ${part.source}`
			}
			return `«${getContent()}»`
		case 'inline-quote':
			return `«${getContent()}»`
		case 'spoiler':
			return `(${getContent()})`
		case 'attachment':
			const attachment = options.attachments.find(_ => _.id === part.attachmentId)
			if (!attachment) {
				return ''
			}
			if (!options.messages) {
				return ''
			}
			return getAttachmentText(attachment, options.messages) || ''
		default:
			return getContent()
	}
}

export function removeQuotes(content) {
	const newContent = removeQuote(content)
	if (newContent === content) {
		return content
	}
	return removeQuote(newContent)
}

export function removePostLinks(content) {
	const newContent = removePostLink(content)
	if (newContent === content) {
		return content
	}
	return removePostLink(newContent)
}

function removeQuote(content) {
	const inlineQuote = content.find(part => typeof part === 'object' && part.type === 'inline-quote')
	if (inlineQuote) {
		const inlineQuoteIndex = content.indexOf(inlineQuote)
		const hasNewLine = content[inlineQuoteIndex + 1] === '\n'
		return content.slice(0, inlineQuoteIndex).concat(content.slice(inlineQuoteIndex + (hasNewLine ? 2 : 1)))
	}
	const quote = content.find(part => typeof part === 'object' && part.type === 'quote')
	if (quote) {
		const quoteIndex = content.indexOf(quote)
		return content.slice(0, quoteIndex).concat(content.slice(quoteIndex + 1))
	}
	return content
}

function removePostLink(content) {
	const postLink = content.find(part => typeof part === 'object' && part.type === 'post-link')
	if (!postLink) {
		return content
	}
	const postLinkIndex = content.indexOf(postLink)
	let hasNewLine = false
	let hasAutomaticQuote = false
	let hasNewLineAfterAutomaticQuote = false
	if (content[postLinkIndex + 1] === '\n') {
		hasNewLine = true
		const possibleAutomaticQuote = content[postLinkIndex + 2]
		if (typeof possibleAutomaticQuote === 'object' && possibleAutomaticQuote.autogenerated) {
			hasAutomaticQuote = true
			if (content[postLinkIndex + 3] === '\n') {
				hasNewLineAfterAutomaticQuote = true
			}
		}
	}
	return content.slice(0, postLinkIndex).concat(content.slice(
		hasAutomaticQuote ?
			(hasNewLineAfterAutomaticQuote ? postLinkIndex + 4 : postLinkIndex + 3) :
			(hasNewLine ? postLinkIndex + 2 : postLinkIndex + 1)
	))
}

function getAttachmentText(attachment, messages) {
	switch (attachment.type) {
		case 'picture':
			if (attachment.picture.title) {
				return attachment.picture.title
			}
			break
		case 'video':
			if (attachment.video.title) {
				return attachment.video.title
			}
			break
	}
	return getAttachmentMessage(attachment, messages)
}

function getAttachmentMessage(attachment, messages) {
	switch (attachment.type) {
		case 'picture':
			return messages.attachmentPicture
		case 'video':
			return messages.attachmentVideo
	}
}