import expectToEqual from './expectToEqual'

export default function(getPostText) {
	function getPostTextTest(content, options, text) {
		if (text === undefined) {
			text = options
			options = {}
		}
		expectToEqual(getPostText({ content }, options), text)
	}

	getPostTextTest(
		'Abc',
		'Abc'
	)

	getPostTextTest(
		['Abc'],
		'Abc'
	)

	getPostTextTest(
		[['Abc']],
		'Abc'
	)

	getPostTextTest(
		['Abc', 'Def'],
		'Abc\n\nDef'
	)

	getPostTextTest(
		[['Abc', 'Def']],
		'AbcDef'
	)

	getPostTextTest(
		[['Abc', '\n', 'Def']],
		'Abc\nDef'
	)

	getPostTextTest(
		[
			[
				{
					type: 'inline-quote',
					content: 'Quote'
				},
				'\n',
				'Abc'
			]
		],
		{
			excludeQuotes: true
		},
		'Abc'
	)

	getPostTextTest(
		[
			{
				type: 'quote',
				content: 'Quote'
			},
			[
				'Abc'
			]
		],
		{
			excludeQuotes: true
		},
		'Abc'
	)

	getPostTextTest(
		[
			[
				{
					type: 'inline-quote',
					content: 'Quote'
				},
				'\n',
				'Abc'
			]
		],
		'«Quote»\nAbc'
	)

	getPostTextTest(
		[
			[
				{
					type: 'text',
					style: 'bold',
					content: [
						{
							type: 'link',
							url: 'https://google.com',
							content: 'Google'
						},
						' ',
						{
							type: 'text',
							style: 'italic',
							content: 'link'
						}
					]
				},
				'\n',
				'Abc'
			]
		],
		'Google link\nAbc'
	)

	getPostTextTest(
		[
			[
				{
					type: 'quote',
					content: [
						{
							type: 'link',
							url: 'https://google.com',
							content: 'Google'
						},
						' ',
						{
							type: 'text',
							style: 'italic',
							content: 'link'
						}
					]
				},
				'\n',
				'Abc'
			]
		],
		'«Google link»\nAbc'
	)
}

export function removePostLinksTest(removePostLinks) {
	function removePostLinksTest(content, text) {
		expectToEqual(removePostLinks(content), text)
	}

	removePostLinksTest(
		[
			{
				type: 'post-link',
				content: 'Сообщение'
			},
			'\n',
			{
				type: 'inline-quote',
				content: 'Quote'
			},
			'\n',
			'abc'
		],
		[
			{
				type: 'inline-quote',
				content: 'Quote'
			},
			'\n',
			'abc'
		]
	)

	removePostLinksTest(
		[
			{
				type: 'post-link',
				content: 'Сообщение'
			},
			'\n',
			{
				type: 'inline-quote',
				content: 'Quote',
				autogenerated: true
			},
			'\n',
			'abc'
		],
		[
			'abc'
		]
	)

	removePostLinksTest(
		[
			{
				type: 'post-link',
				content: 'Сообщение'
			},
			'\n',
			{
				type: 'inline-quote',
				content: 'Quote',
				autogenerated: true
			},
			'\n',
			{
				type: 'post-link',
				content: 'Сообщение'
			},
			'\n',
			{
				type: 'inline-quote',
				content: 'Quote',
				autogenerated: true
			},
			'\n',
			'abc'
		],
		[
			'abc'
		]
	)
}

export function removeQuotesTest(removeQuotes) {
	function removeQuotesTest(content, text) {
		expectToEqual(removeQuotes(content), text)
	}

	removeQuotesTest(
		[
			'123',
			{
				type: 'quote',
				content: 'Сообщение'
			},
			[
				'Abc',
				'\n',
				'Def'
			]
		],
		[
			'123',
			[
				'Abc',
				'\n',
				'Def'
			]
		]
	)

	removeQuotesTest(
		[
			'Abc',
			'\n',
			{
				type: 'inline-quote',
				content: 'Quote'
			},
			'\n',
			'Def'
		],
		[
			'Abc',
			'\n',
			'Def'
		]
	)
}