import test, { removePostLinksTest, removeQuotesTest } from './getPostText.test'

/**
 * Converts post content to text.
 * @param  {object} post
 * @return {string}
 */
export default function getPostText(post, options = {}) {
	if (!post.content) {
		return ''
	}
	// Simple case optimization.
	if (typeof post.content === 'string') {
		return post.content
	}
	// Concatenate post paragraphs' text.
	return post.content.map(_ => getContentText(_, options)).filter(_ => _).join('\n\n')
}

function getContentText(content, options) {
	if (Array.isArray(content)) {
		content = removePostLinks(content)
		if (options.excludeQuotes) {
			content = removeQuotes(content)
		}
		return content.map(_ => getContentText(_, options)).join('')
	}
	if (typeof content === 'string') {
		return content
	}
	const part = content
	content = getContentText(part.content, options)
	switch (part.type) {
		case 'quote':
			if (options.excludeQuotes) {
				return ''
			}
			if (part.source) {
				return `«${content}» — ${part.source}`
			}
			return `«${content}»`
		case 'inline-quote':
			return `«${content}»`
		case 'spoiler':
			return `(${content})`
		default:
			return content
	}
}

function removeQuotes(content) {
	const newContent = removeQuote(content)
	if (newContent === content) {
		return content
	}
	return removeQuote(newContent)
}

function removePostLinks(content) {
	const newContent = removePostLink(content)
	if (newContent === content) {
		return content
	}
	return removePostLink(newContent)
}

function removeQuote(content) {
	const inlineQuote = content.find(part => typeof part === 'object' && part.type === 'inline-quote')
	if (inlineQuote) {
		const inlineQuoteIndex = content.indexOf(inlineQuote)
		const hasNewLine = content[inlineQuoteIndex + 1] === '\n'
		return content.slice(0, inlineQuoteIndex).concat(content.slice(inlineQuoteIndex + (hasNewLine ? 2 : 1)))
	}
	const quote = content.find(part => typeof part === 'object' && part.type === 'quote')
	if (quote) {
		const quoteIndex = content.indexOf(quote)
		return content.slice(0, quoteIndex).concat(content.slice(quoteIndex + 1))
	}
	return content
}

function removePostLink(content) {
	const postLink = content.find(part => typeof part === 'object' && part.type === 'post-link')
	if (!postLink) {
		return content
	}
	const postLinkIndex = content.indexOf(postLink)
	let hasNewLine = false
	let hasAutomaticQuote = false
	let hasNewLineAfterAutomaticQuote = false
	if (content[postLinkIndex + 1] === '\n') {
		hasNewLine = true
		const possibleAutomaticQuote = content[postLinkIndex + 2]
		if (typeof possibleAutomaticQuote === 'object' && possibleAutomaticQuote.autogenerated) {
			hasAutomaticQuote = true
			if (content[postLinkIndex + 3] === '\n') {
				hasNewLineAfterAutomaticQuote = true
			}
		}
	}
	return content.slice(0, postLinkIndex).concat(content.slice(
		hasAutomaticQuote ?
			(hasNewLineAfterAutomaticQuote ? postLinkIndex + 4 : postLinkIndex + 3) :
			(hasNewLine ? postLinkIndex + 2 : postLinkIndex + 1)
	))
}

removePostLinksTest(removePostLinks)
removeQuotesTest(removeQuotes)
test(getPostText)