import React from 'react'
import PropTypes from 'prop-types'

import PostMonospace from './PostMonospace'
import PostInlineQuote from './PostInlineQuote'
import PostInlineSpoiler from './PostInlineSpoiler'
import PostText from './PostText'
import PostLink from './PostLink'
import PostReadMore from './PostReadMore'

import { postParagraph, postInlineElement } from '../PropTypes'

export default function PostInlineContent({
	children,
	...rest
}) {
	if (typeof children === 'string') {
		return children
	}
	return children.map((content, i) => (
		<PostInlineContentElement
			key={i}
			{...rest}>
			{content}
		</PostInlineContentElement>
	))
}

PostInlineContent.propTypes = {
	url: PropTypes.string,
	onReadMore: PropTypes.func.isRequired,
	readMoreLabel: PropTypes.string,
	openSlideshow: PropTypes.func,
	serviceIcons: PropTypes.objectOf(PropTypes.func),
	children: postParagraph.isRequired
}

function PostInlineContentElement({ children: content, ...rest }) {
	const {
		url,
		onReadMore,
		readMoreLabel,
		openSlideshow,
		serviceIcons
	} = rest
	if (content === '\n') {
		return <br/>
	} else if (Array.isArray(content) || typeof content === 'string') {
		return (
			<PostInlineContent {...rest}>
				{content}
			</PostInlineContent>
		)
	}
	const _content = content.content && (
		<PostInlineContentElement {...rest}>
			{content.content}
		</PostInlineContentElement>
	)
	if (content.type === 'text') {
		return (
			<PostText style={content.style}>
				{_content}
			</PostText>
		)
	} else if (content.type === 'inline-quote') {
		return (
			<PostInlineQuote
				kind={content.kind}
				autogenerated={content.autogenerated}>
				{_content}
			</PostInlineQuote>
		)
	} else if (content.type === 'spoiler') {
		return (
			<PostInlineSpoiler
				censored={content.censored}
				content={content.content}>
				{_content}
			</PostInlineSpoiler>
		)
	} else if (content.type === 'post-link') {
		if (content.quote || content.quotes) {
			const children = content.quote ? (
				<PostInlineContentElement {...rest}>
					{content.quote}
				</PostInlineContentElement>
			) : content.quotes.map((quote, i) => (
				<PostInlineContentElement key={i} {...rest}>
					{quote}
				</PostInlineContentElement>
			))
			return (
				<PostInlineQuote
					url={content.url}
					kind={content.quoteKind}
					kinds={content.quoteKinds}
					autogenerated={content.quoteAutogenerated}>
					{children}
				</PostInlineQuote>
			)
		}
		return (
			<PostLink
				url={content.url}
				className="post__link--post">
				{_content}
			</PostLink>
		)
	} else if (content.type === 'link') {
		return (
			<PostLink
				url={content.url}
				autogenerated={content.autogenerated}
				attachment={content.attachment}
				service={content.service}
				openSlideshow={openSlideshow}
				serviceIcons={serviceIcons}>
				{_content}
			</PostLink>
		)
	} else if (content.type === 'monospace') {
		return (
			<PostMonospace inline>
				{_content}
			</PostMonospace>
		)
	} else if (content.type === 'read-more') {
		return (
			<React.Fragment>
				{' '}
				<PostReadMore
					url={url}
					onReadMore={onReadMore}
					readMoreLabel={readMoreLabel}/>
			</React.Fragment>
		)
	} else {
		console.error(`Unsupported post inline content:\n`, content)
		return null
	}
}

PostInlineContentElement.propTypes = {
	...PostInlineContent.propTypes,
	children: postInlineElement.isRequired
}