import React from 'react'
import PropTypes from 'prop-types'
import { Link } from 'react-website'
import classNames from 'classnames'

import { postInlineQuote } from '../PropTypes'

import './PostInlineQuote.css'

export default function PostInlineQuote({ url, autogenerated, children }) {
	if (url) {
		if (url[0] === '/') {
			return (
				<Link
					to={url}
					className="post__inline-quote">
					<Quote autogenerated={autogenerated}>
						{children}
					</Quote>
				</Link>
			)
		}
		return (
			<a
				target={url[0] === '#' ? undefined : '_blank'}
				href={url}
				className="post__inline-quote">
				<Quote autogenerated={autogenerated}>
					{children}
				</Quote>
			</a>
		)
	}
	return (
		<Quote autogenerated={autogenerated} className="post__inline-quote">
			{children}
		</Quote>
	)
}

PostInlineQuote.propTypes = {
	url: PropTypes.string,
	autogenerated: PropTypes.bool,
	content: PropTypes.node.isRequired
}

function Quote({ autogenerated, className, children }) {
	return (
		<q
			className={classNames(className, 'post__inline-quote-text', {
				'post__inline-quote-text--autogenerated': autogenerated
			})}>
			{children}
		</q>
	)
}

Quote.propTypes = {
	autogenerated: PropTypes.bool,
	content: PropTypes.node.isRequired,
	className: PropTypes.string
}