import React from 'react'
import PropTypes from 'prop-types'
import classNames from 'classnames'

import { postInlineQuote } from '../PropTypes'

import './PostInlineQuote.css'

export default function PostInlineQuote({ autogenerated, children }) {
	return (
		<q
			className={classNames('post__inline-quote', {
				'post__inline-quote--autogenerated': autogenerated
			})}>
			{children}
		</q>
	)
}

PostInlineQuote.propTypes = {
	autogenerated: PropTypes.bool,
	content: PropTypes.node.isRequired
}
