/**
 * Removes leading `post-link`s to `parentPost` from `post.content`.
 * Is used before showing an expanded parent post replies branch.
 * @param  {object} post
 * @param  {object} parentPost — The "parent" post. The post for which the `post` is a reply.
 */
export default function removeLeadingPostLink(post, parentPost) {
	const content = removeLeadingPostLinkFromContent(post.content, parentPost.id)
	if (content === post.content) {
		return post
	}
	return {
		...post,
		content
	}
}

function removeLeadingPostLinkFromContent(content, parentPostId) {
	if (content) {
		const paragraph = content[0]
		if (Array.isArray(paragraph)) {
			const firstPart = paragraph[0]
			if (typeof firstPart === 'object' &&
				firstPart.type === 'post-link' &&
				firstPart.postId === parentPostId) {
				const postLinkHasQuotes = Array.isArray(firstPart.content) && firstPart.content[0].type === 'quote'
				// Only remove autogenerated `post-link`s.
				// If a `post-link` contains a quote posted manually
				// by the post author then don't remove such quote.
				// If a post link content is not a "quote" then
				// it's something autogenerated like "Comment".
				const postLinkIsAutogenerated = firstPart.quoteAutogenerated || !postLinkHasQuotes
				if (postLinkIsAutogenerated) {
					if (paragraph.length === 1) {
						if (content.length === 1) {
							return
						} else {
							return content.slice(1)
						}
					} else if (paragraph[1] === '\n') {
						if (paragraph.length === 2) {
							if (content.length === 1) {
								return
							} else {
								return content.slice(1)
							}
						} else {
							if (content.length === 1) {
								return [paragraph.slice(2)]
							} else {
								return [paragraph.slice(2)].concat(content.slice(1))
							}
						}
					}
				}
			}
		}
	}
	return content
}